### ISSUE TITLE
warnings generating myipcore_demo

### ISSUE THREAD

**Issue by ghost** [myriadrf/LimeSDR-PCIe_GW#2]
I followed the procedure in doc/Xillybus_core_gen_guide_V01r00.pdf exactly.
And I receive 3 warnings, are they safe to ignore ?
- xillybus_read_32: This stream can generate about 24900 interrupts per second to the host, which may degrade its performance. An interrupt is sent every time a DMA buffer is filled or emptied. It's therefore recommended to make each DMA buffer larger.
- xillybus_write_32: This stream can generate about 23000 interrupts per second to the host, which may degrade its performance. An interrupt is sent every time a DMA buffer is filled or emptied. It's therefore recommended to make each DMA buffer larger.
- xillybus_write_32: It's recommended to enable DMA acceleration to better meet your bandwidth expectations.

https://i.imgur.com/ElSfpkX.png?1

**Comment by ztamosevicius** [comment]
These warnings are safe. If buffers will be larger, then data latency will be higher.

**Comment by ghost** [comment]
Thanks
