### ISSUE TITLE
compiling problems

### ISSUE THREAD

**Issue by cseran** [myriadrf/LimeSDR-PCIe_GW#3]
I have just tried to compile,did everything as explained in the docs but having always:
Error (170012): Fitter requires 1864 LABs to implement the design, but the device contains only 1840 LABs

and then compiling stops..

Any idea?? or we trash our SDR card?

**Comment by vbuitvydas** [comment]
What Quartus version are you using? Try Quartus prime, Version 15.1.2 Build 193 02/01/2016 SJ Lite Edition as mentioned in /doc/LimeSDR-PCIe_Gateware_Description_v01r00.pdf "Introduction" section. Newer versions of Quartus might give different resource count after synthesis and because of that design can fail to fit.

**Comment by cseran** [comment]
Hi vbuitvydas 
Thanks for informing!! i did not pay attention to the version and used the latest version which does not fit the design..


However using 15.1.2 did not resolve my problem..

Let me explain:

I received a LimeSDR PCie card some time ago, in fact, to my company i am working.

I attached to a PC running amarisoft stack, configured as explained in the documents...

Even it worked perfect, and some mobiles attach to the LTE Coverage..


Until here it's good!!

But when I try to calibrate the LimeSDR Pcie, i found out that i attached the antenna to the wrong port, while trying to change the antenna port, ( i do not have any idea if ) something went wrong..

I restarted the PC!

Now Amarisoft or LimeSDR all it says: "No device found" although it's connected to PCie..

At first I assumed that the image is corrupted; that's why I was trying to flash again. 
Now I re flashed with the *.jic file generated by Quartus, but no luck still says "No device found".

I have lost the card?? 
Is there any way to recover?

I tried to contact LimeSDR but no luck, there is no support..

Thanks for helping!!

**Comment by cseran** [comment]
and led is blinking green -red -green -red - and so on..
and Limeutil --find finds nothing..

**Comment by vbuitvydas** [comment]
Blinking LED indicates that gateware is loaded and running on FPGA so there seems to be no problems with FPGA. 

Could it be that you accidentally pushed board out of position while connecting antennas? Check if your board is installed properly in PCIe slot. 

As i understand you can successfully reprogram FPGA with Quartus, can you try following procedure: 
1. Enter BIOS on your PC where LimeSDR-PCIe card is installed;
2. While on BIOS program LimeSDR-PCIe board with .sof programming file from gateware project. 
3. Exit BIOS and check if board is detected.

**Comment by cseran** [comment]
i entered in bios.  
i am supposed to use quartus to program with .sof?
thx

**Comment by cseran** [comment]
i did what you have suggested 
in bios, i flashed with .sof, said successful in quartus
restarted,
still no devices found..

**Comment by vbuitvydas** [comment]
Closing this because issue is not related to compiling problems, project can be compiled by using Quartus prime, Version 15.1.2 Build 193 02/01/2016 SJ Lite Edition as mentioned in /doc/LimeSDR-PCIe_Gateware_Description_v01r00.pdf "Introduction" section.
